FROM node:12-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN yarn cache clean
RUN yarn
RUN yarn global add ts-node
RUN yarn global add ts-node-dev 
RUN yarn global add typescript
ENV REACT_APP_BASE_URL=http://localhost:5000
COPY . .
CMD ["yarn", "run", "dev"]